web: python manage.py -c ProdConfig runserver --host 0.0.0.0 --port ${PORT}
init: python manage.py -c ProdConfig db init
migrate: python manage.py -c ProdConfig db migrate
upgrade: python manage.py -c ProdConfig db upgrade
