"""empty message

Revision ID: 0afc4e7a2fdb
Revises: ef937845bf39
Create Date: 2019-12-01 22:37:43.136730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afc4e7a2fdb'
down_revision = 'ef937845bf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
