"""empty message

Revision ID: 5bb753febb4c
Revises: 0afc4e7a2fdb
Create Date: 2019-12-02 00:18:59.151977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb753febb4c'
down_revision = '0afc4e7a2fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_day', sa.Column('breakfast_portion', sa.Float(), nullable=True))
    op.add_column('diet_day', sa.Column('dinner_portion', sa.Float(), nullable=True))
    op.add_column('diet_day', sa.Column('lunch_portion', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diet_day', 'lunch_portion')
    op.drop_column('diet_day', 'dinner_portion')
    op.drop_column('diet_day', 'breakfast_portion')
    # ### end Alembic commands ###
