"""empty message

Revision ID: ef937845bf39
Revises: 62747d6b6e6d
Create Date: 2019-12-01 18:39:54.191635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef937845bf39'
down_revision = '62747d6b6e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diet_id', sa.Integer(), nullable=True),
    sa.Column('is_complex', sa.Boolean(), nullable=True),
    sa.Column('breakfast', sa.String(length=128), nullable=True),
    sa.Column('lunch', sa.String(length=128), nullable=True),
    sa.Column('dinner', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet_day')
    op.drop_table('diet')
    # ### end Alembic commands ###
